"""Published metrics must match the code that produced them.

GLOBAL_RULESET R9.1 says every accuracy, coverage, latency and throughput figure
in ``README.md``, ``docs/ARCHITECTURE.md``, the slides and the UI comes from
``reports/metrics/*.json``, regenerated by one command. That rule is only worth
anything if something notices when it is broken, and nothing about a stale number
looks wrong: a README claiming "71 of 90 CIS controls" reads identically whether
it was measured this morning or two rule packs ago.

So this file is the gate. It shells out to ``scripts/bench/run_all.py --check``,
which re-measures everything and diffs the substance — counts, coverage ratios,
control totals, abstention rates — against what is on disk, ignoring wall-clock
timings and the machine fingerprint (see ``scripts/bench/__init__.py:VOLATILE``).
Add a rule, change a pattern, retrain a classifier: this goes red in the same run
as the rest of the suite, and the fix is one command.

Why a subprocess and not an import
----------------------------------
The bench scripts are built to run standalone: they insert the project root on
``sys.path`` at import, cache module-scope state, and ``bench_pdf_gen`` swaps
``builtins.__import__`` to prove the ReportLab fallback works. Importing them into
the pytest process would share those mutations with 900 other tests. It would also
invalidate the measurements themselves, since the point of one-process-per-script
is that no script inherits caches another paid for.

The cost is the honest one: this is the slowest test in the suite by an order of
magnitude, because it genuinely re-runs every benchmark. It is marked ``slow`` so
``-m "not slow"`` skips it during a tight edit loop, and it is the last thing that
should be skipped before a submission.
"""

from __future__ import annotations

import json
import subprocess
import sys

import pytest

from backend.app.config import PROJECT_ROOT

BENCH_DIR = PROJECT_ROOT / "scripts" / "bench"
METRICS_DIR = PROJECT_ROOT / "reports" / "metrics"

#: The envelope R9.2 requires of every metric file.
REQUIRED_KEYS = ("metric", "measures", "dataset", "n", "generated_at", "environment", "results")

#: Files in ``reports/metrics/`` that ``run_all.py`` writes and therefore must
#: carry the R9.2 envelope.
BENCH_FILES = (
    "parse_coverage.json",
    "rule_latency.json",
    "ai_abstention.json",
    "pdf_generation.json",
)

#: Files in ``reports/metrics/`` that are raw *training* output rather than
#: benchmarks. These legitimately have no R9.2 envelope: they were written by a
#: training script recording what it did, not by a measurement harness, and
#: retrofitting a fake ``n``/``dataset``/``environment`` onto them would make them
#: look like measurements they are not.
#:
#: The list is explicit so that omission cannot be how a file escapes the
#: envelope. A new bench output that forgot its envelope is not on this list and
#: fails :meth:`TestTrainingOutputIsNotMistakenForABenchmark.test_no_file_escapes_the_envelope_by_accident`.
TRAINING_FILES = ("classifier.json", "qlora.json", "setfit.json")

#: Files in ``reports/metrics/`` that are a *register* — a complete enumeration of
#: something in the repository rather than a measurement of it.
#:
#: ``unverified.json`` lists every R1.5 verification marker in the tree. It has no
#: R9.2 envelope and should not be given one: there is no sample, so ``n`` would
#: restate the length of ``register``; there is no dataset, because the dataset is
#: the repository at that commit; and there is no ``environment``, because the
#: result does not depend on the machine that produced it. Bolting those fields on
#: would make a census look like a benchmark, which is the precise confusion this
#: class exists to prevent — just running the other way.
#:
#: The envelope is not what makes it trustworthy; being recomputed is. That
#: happens in ``tests/test_unverified_register.py``, which re-scans the tree and
#: diffs this file against the result, so a stale register fails the suite exactly
#: as a stale benchmark does.
#:
#: ``attack_coverage.json`` is the same shape of thing one level out: the complete
#: join of the 454-rule pack onto ``data/frameworks/attack/canonical_map.yaml``.
#: It is a census of the rule pack, not a sample from it — ``n`` would restate
#: ``rules_total``, the dataset is the rule pack at that commit, and the join is
#: pure set arithmetic over canonical paths, so it cannot vary with the machine.
#: Giving it an ``environment`` block would imply a timing or accuracy claim that
#: nothing here makes.
#:
#: It is recomputed the same way, by
#: ``tests/test_threat_mapping.py::test_published_metric_matches_the_measurement``
#: and by ``scripts/attack_coverage.py --check``, which additionally fails on a
#: mapped prefix that matches no rule.
REGISTER_FILES = ("unverified.json", "attack_coverage.json")


def _benchmark_names() -> list[str]:
    """Read the runner's own list so this test cannot fall behind it.

    Parsed out of the source rather than imported, for the same reason the runner
    is invoked as a subprocess. A hardcoded copy here would drift the moment a
    fifth benchmark landed, and it would drift silently — the test would keep
    passing while checking four of five files.
    """
    source = (BENCH_DIR / "run_all.py").read_text(encoding="utf-8")
    block = source.split("BENCHMARKS = [", 1)[1].split("]", 1)[0]
    return [line.strip().strip('",') for line in block.splitlines() if line.strip().startswith('"')]


class TestEveryMetricFileIsWellFormed:
    """Cheap structural checks, so a malformed file fails fast and legibly."""

    def test_every_benchmark_has_published_a_file(self) -> None:
        """A missing file means a number in the docs has no source at all."""
        names = _benchmark_names()
        assert len(names) >= 4, f"only parsed {names} out of run_all.py"
        published = {p.name for p in METRICS_DIR.glob("*.json")}
        assert published, f"{METRICS_DIR} is empty — run scripts/bench/run_all.py"

    @pytest.mark.parametrize("filename", BENCH_FILES)
    def test_the_r9_2_envelope_is_present(self, filename: str) -> None:
        """What was measured, on what data, at what N, when, on what hardware."""
        path = METRICS_DIR / filename
        assert path.exists(), f"{filename} is missing — run scripts/bench/run_all.py"
        payload = json.loads(path.read_text(encoding="utf-8"))
        missing = [key for key in REQUIRED_KEYS if key not in payload]
        assert not missing, f"{filename} is missing R9.2 fields: {missing}"
        assert payload["n"] > 0, f"{filename} claims N={payload['n']}"
        assert payload["environment"].get("platform"), f"{filename} has no platform recorded"

    @pytest.mark.parametrize("filename", BENCH_FILES)
    def test_no_metric_claims_to_be_without_limitations(self, filename: str) -> None:
        """R9.4: an empty ``caveats`` list is a claim, and a false one.

        Every measurement in this project has limits — single vendor, fixtures
        written alongside the parser, one machine, no held-out split. A metric file
        with nothing in ``caveats`` is asserting that its number transfers
        unconditionally, which is the specific overclaim R9.4 exists to prevent.
        """
        payload = json.loads((METRICS_DIR / filename).read_text(encoding="utf-8"))
        assert payload.get("caveats"), (
            f"{filename} publishes no caveats. Either the measurement has "
            "limitations that are being hidden, or it is the first number in this "
            "project that transfers unconditionally -- which it is not."
        )


class TestConfigurationIsNotConfusedWithStaleness:
    """``check()`` must distinguish "the code moved" from "this machine differs".

    ``ai_abstention.json`` is the only metric whose numbers depend on the machine
    as well as the code: the abstention rate with a llama-server up is a different
    true number from the one with it down. Before this branch existed, starting a
    model server made the gate report the published figure *stale* and demand a
    regeneration that would have overwritten a deliberate publication with an
    accident of local process state.

    The exemption is narrow and these tests are what keeps it narrow: a mismatched
    configuration passes, and everything else about the same file is still gated.
    """

    def _payload(self, **overrides: object) -> dict:
        payload = json.loads(
            (METRICS_DIR / "ai_abstention.json").read_text(encoding="utf-8")
        )
        payload.update(overrides)
        return payload

    def test_the_published_metric_declares_its_configuration(self) -> None:
        """Without the declaration the branch below can never fire."""
        payload = self._payload()
        assert "configuration" in payload, (
            "ai_abstention.json publishes no `configuration`, so scripts/bench "
            "cannot tell a different machine from a stale measurement."
        )
        assert "tiers_available" in payload["configuration"]

    def test_a_different_tier_configuration_is_not_reported_as_stale(self) -> None:
        """Starting llama-server must not turn the gate red."""
        from scripts.bench import check

        fresh = self._payload()
        fresh["configuration"] = {"tiers_available": {"tier1": True, "tier2": True, "tier3": True}}
        assert check(fresh, filename="ai_abstention.json") == 0

    def test_a_matching_configuration_still_gates_the_substance(self) -> None:
        """The escape hatch must not swallow a genuinely stale number."""
        from scripts.bench import check

        fresh = self._payload()
        # Same configuration, moved result: this is the staleness the gate exists
        # for, and it must still fail.
        fresh["results"] = dict(fresh["results"], canonical_paths_published=1)
        assert check(fresh, filename="ai_abstention.json") == 1

    def test_only_metrics_that_need_it_declare_a_configuration(self) -> None:
        """One exemption is a considered decision; five is a habit.

        Every other metric is a pure function of the repository, so declaring a
        configuration there would exempt it from the gate for no reason anyone
        could state. If a second file ever needs one, that is a real argument to
        make in review rather than a line to add quietly.
        """
        declared = sorted(
            path.name
            for path in METRICS_DIR.glob("*.json")
            if "configuration" in json.loads(path.read_text(encoding="utf-8"))
        )
        assert declared == ["ai_abstention.json"], (
            f"{declared} declare a `configuration`, which exempts them from "
            "--check whenever this machine differs. Only ai_abstention.json has "
            "an argument for that: its numbers genuinely change with which model "
            "tiers are up. Anything else is a gate being quietly switched off."
        )


class TestTrainingOutputIsNotMistakenForABenchmark:
    """``classifier.json`` reports ``mean_accuracy: 0.959``. On its own that lies.

    Not because the number is wrong — the cross-validation ran and produced it —
    but because of what it invites the reader to conclude. 1,581 of the 1,943
    samples are a single class, so a constant predictor that ignores its input
    entirely scores about 0.814 on the same split. Quoted alone, "95.9% accurate"
    reads as competence when most of it is class imbalance, and the lift over
    doing nothing is roughly 14 points.

    There is a second, worse problem the number hides: the training labels were
    generated by running the *deterministic parsers* over the corpus
    (``scripts/train_classifier.py:_generate_labels_from_corpus``). So the metric
    measures agreement with a regex on lines the regex already handles. C2 needs
    the opposite — classifying formats the parsers have never seen — and this
    figure is structurally incapable of speaking to it.

    A comment in the README is not enough to hold that line, because the failure
    mode is a person under deadline copying the highest number in the directory
    onto a slide. So the baseline is recomputed here from the file's own class
    supports, and the README is required to contain it. Delete the caveat and this
    goes red.
    """

    def _classifier(self) -> dict:
        path = METRICS_DIR / "classifier.json"
        assert path.exists(), "classifier.json is missing; it records a training run"
        return json.loads(path.read_text(encoding="utf-8"))

    def test_no_file_escapes_the_envelope_by_accident(self) -> None:
        """Every file is either a checked benchmark, a training record or a register.

        The point is to close the fourth category: a file that is none of them,
        which would be a published number nothing structurally checks. That is
        what ``classifier.json`` was before this test existed.

        Each of the three lists is explicit, so omission cannot be how a file
        escapes — and each carries the argument for why it is exempt from the
        envelope, so the exemption can be disagreed with rather than merely
        discovered.
        """
        published = {p.name for p in METRICS_DIR.glob("*.json")}
        unaccounted = (
            published - set(BENCH_FILES) - set(TRAINING_FILES) - set(REGISTER_FILES)
        )
        assert not unaccounted, (
            f"{sorted(unaccounted)} in reports/metrics/ is not declared in "
            f"BENCH_FILES, TRAINING_FILES or REGISTER_FILES. If it is a benchmark "
            f"it needs the R9.2 envelope and caveats; otherwise add it to the list "
            f"that fits and write down why the envelope does not apply, so the "
            f"exemption is deliberate rather than accidental."
        )

    def test_the_majority_class_baseline_is_what_the_readme_says(self) -> None:
        """Recompute the baseline from the file's own supports.

        Derived rather than hardcoded, so retraining on a differently-balanced
        corpus moves the assertion instead of silently invalidating it.

        ``per_class`` is a dumped sklearn ``classification_report``, so it also
        contains ``macro avg`` and ``weighted avg`` rows whose support is the whole
        sample count. Those are filtered by membership in the file's own
        ``classes`` list rather than by name, because filtering on the strings
        sklearn happens to use would break the day it renames them — and it would
        break by silently computing a baseline of 1.0, which reads as "no lift at
        all" rather than as an error.
        """
        payload = self._classifier()
        classes = set(payload["classes"])
        supports = {
            name: row["support"]
            for name, row in payload["per_class"].items()
            if name in classes
        }

        assert len(supports) == payload["n_classes"], (
            f"per_class covers {len(supports)} of {payload['n_classes']} declared "
            f"classes; missing {sorted(classes - set(supports))}"
        )
        assert sum(supports.values()) == payload["n_samples"], (
            f"class supports sum to {sum(supports.values())} but n_samples is "
            f"{payload['n_samples']} -- an aggregate row is being counted as a class"
        )

        baseline = max(supports.values()) / payload["n_samples"]
        assert 0.80 < baseline < 0.83, (
            f"the majority-class baseline moved to {baseline:.4f}; the README's "
            f"0.814 and the ~14-point lift both need updating"
        )
        assert payload["mean_accuracy"] - baseline < 0.20, (
            "accuracy now exceeds the majority-class baseline by more than 20 "
            "points, which would be a real result worth restating rather than "
            "caveating -- check whether the corpus was rebalanced"
        )

    def test_the_readme_publishes_the_baseline_beside_the_accuracy(self) -> None:
        """The accuracy may not appear in the README without its correction.

        Asserted on proximity, not just presence: both figures being *somewhere*
        in a 280-line file is not the same as a reader seeing them together, and
        it is being seen together that stops the misreading.
        """
        readme = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
        if "0.959" not in readme:
            pytest.skip("README no longer quotes the classifier accuracy at all")

        window_start = max(0, readme.index("0.959") - 1200)
        window = readme[window_start : readme.index("0.959") + 1200]
        assert "0.814" in window, (
            "README.md quotes the classifier's 0.959 accuracy without the "
            "majority-class baseline (0.814) nearby. The baseline is what makes "
            "the accuracy readable; without it the number overstates the model by "
            "about 82 points. See TestTrainingOutputIsNotMistakenForABenchmark."
        )

    def test_the_setfit_record_cannot_publish_a_perfect_score_bare(self) -> None:
        """``setfit.json`` reports ``accuracy: 1.0``. That is true and nearly empty.

        The Tier 2 fine-tune got all 493 held-out lines right, so the number is not
        wrong. It is close to uninformative: 464 of those 493 are
        ``interface.admin_state``, and only 7 of the 14 trained classes appear in
        the holdout at all. A device-grouped split is the right split — it is the
        one that stops the score measuring memorisation of near-identical interface
        stanzas — but on a corpus that is 81% one class, grouping by device cannot
        also balance the holdout. So the split trades a leak for an imbalance, and
        the imbalance is what the reader has to be told.

        A perfect score is the single most quotable number in the whole metrics
        directory, which is exactly why it needs a structural guard rather than a
        comment. This asserts the file carries its own correction: the majority
        share, the measured-class count, and prose saying what the number does not
        establish. Retraining on a rebalanced corpus is the way to make the
        assertion relax, and it will relax on its own — the threshold is derived
        from the file's own distribution, not hardcoded.
        """
        path = METRICS_DIR / "setfit.json"
        assert path.exists(), (
            "setfit.json is missing. Tier 2 is trained by scripts/train_setfit.py "
            "(MANUAL_COMMANDS.md Step 8c); the model and its record ship together, "
            "because a tier whose artefact has no measurement behind it is what "
            "Tier 2 already was once."
        )
        payload = json.loads(path.read_text(encoding="utf-8"))

        distribution = payload.get("holdout_distribution") or {}
        assert distribution, "setfit.json publishes no holdout_distribution"
        assert sum(distribution.values()) == payload["n_holdout"], (
            f"holdout_distribution sums to {sum(distribution.values())} but "
            f"n_holdout is {payload['n_holdout']}"
        )

        share = max(distribution.values()) / payload["n_holdout"]
        assert payload["majority_class_share_pct"] == pytest.approx(share * 100, abs=0.1), (
            "majority_class_share_pct disagrees with holdout_distribution"
        )

        # The guard only has to hold while the split is actually lopsided. Rebalance
        # the corpus and this test stops demanding a caveat, which is the correct
        # behaviour: the caveat exists because of the imbalance, not on principle.
        if share < 0.5 and payload["n_classes_measured"] == payload["n_classes"]:
            return

        assert payload.get("caveat"), (
            f"setfit.json publishes accuracy={payload.get('accuracy')} on a holdout "
            f"that is {share:.1%} one class, with no caveat field. The number will "
            "be copied onto a slide as 'Tier 2 is 100% accurate'."
        )
        caveat = payload["caveat"]
        assert payload["majority_class"] in caveat, (
            "the caveat does not name the class that dominates the holdout"
        )
        assert str(payload["n_classes_measured"]) in caveat, (
            f"the caveat does not say that only {payload['n_classes_measured']} of "
            f"{payload['n_classes']} trained classes were measured"
        )

    def test_the_setfit_model_is_written_where_the_loader_reads_it(self) -> None:
        """The trainer's default output path must be the loader's constant.

        This is the defect that kept Tier 2 dark: ``backend/ai/setfit_clf.py``
        checked ``data/models/classifier/setfit_model`` for availability, and no
        script in the project wrote it — ``train_classifier.py`` trains Tier 1 only,
        despite a name that reads as covering both. ``is_available()`` was therefore
        correct and permanently ``False``, the ladder silently ran two tiers, and
        nothing failed, because a missing tier is indistinguishable from a
        deliberately absent one.

        Asserted against the imported constant on both sides so the two cannot be
        edited apart. ``argparse`` defaults are read off the parser rather than by
        running the trainer, which needs ``setfit`` and ``torch`` installed.
        """
        from backend.ai.setfit_clf import SETFIT_MODEL_PATH

        source = (PROJECT_ROOT / "scripts" / "train_setfit.py").read_text(encoding="utf-8")
        assert "from backend.ai.setfit_clf import SETFIT_MODEL_PATH" in source, (
            "scripts/train_setfit.py no longer imports the loader's path constant. "
            "Retyping the path here is how the trainer and the loader drifted apart "
            "in the first place."
        )
        assert "default=SETFIT_MODEL_PATH" in source, (
            "--out no longer defaults to SETFIT_MODEL_PATH, so a default run trains "
            "a model the loader will not find"
        )
        assert SETFIT_MODEL_PATH.name == "setfit_model", SETFIT_MODEL_PATH

    def test_the_qlora_record_does_not_claim_an_accuracy(self) -> None:
        """Tier 3's record publishes losses, and must not grow an accuracy field.

        ``qlora.json`` is a training log: 3 epochs, ``eval_loss`` 0.249, on the
        same parser-generated labels. An accuracy appearing in it later would be
        measured on that same circular split and would be quoted the same way the
        0.959 nearly was, so the absence is worth pinning while it is still true.
        """
        payload = json.loads((METRICS_DIR / "qlora.json").read_text(encoding="utf-8"))
        claims = [k for k in payload if "accuracy" in k.lower() or "f1" in k.lower()]
        assert not claims, (
            f"qlora.json now publishes {claims}. If tier 3 was genuinely "
            f"evaluated, give it the R9.2 envelope and caveats and move it into "
            f"BENCH_FILES; do not ship a bare accuracy from a training script."
        )


@pytest.mark.slow
class TestPublishedNumbersMatchTheCode:
    """The gate itself. Slow, and the reason the file exists."""

    def test_run_all_check_passes(self) -> None:
        """Re-measure everything and diff the substance against what is on disk.

        The assertion message is the runner's own output, unmodified, because it
        already names each metric that moved and each key within it. Summarising it
        here would mean re-deriving information the subprocess computed.
        """
        proc = subprocess.run(
            [sys.executable, str(BENCH_DIR / "run_all.py"), "--check"],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=600,
            check=False,
        )
        assert proc.returncode == 0, (
            "A published metric no longer matches the code.\n\n"
            f"{proc.stdout}\n{proc.stderr}\n"
            "Regenerate with:\n"
            "    .venv/Scripts/python.exe scripts/bench/run_all.py\n"
            "then update any figure in README.md or docs/ARCHITECTURE.md that moved."
        )

    def test_the_runner_rejects_an_unknown_benchmark(self) -> None:
        """Exit 2 and a list of what it does know, rather than silently doing nothing.

        Included because ``--only`` is the flag someone reaches for when a single
        metric is failing, and a typo that exits 0 having run nothing would read as
        "fixed".
        """
        proc = subprocess.run(
            [sys.executable, str(BENCH_DIR / "run_all.py"), "--only", "bench_nonexistent"],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60,
            check=False,
        )
        assert proc.returncode == 2
        assert "unknown benchmark" in proc.stderr
        assert "bench_parse_coverage" in proc.stderr, "the error should list valid names"
