"""Test: the counts this project publishes about *itself* must be current.

`README.md`, the slide deck and the presenter's script all quote a test count and
a canonical-path count. Both are load-bearing credibility claims — "1,149 tests
green" is the sentence that turns "we built a prototype" into "we built a
prototype you can check" — and both had drifted, in four different directions at
once:

    MANUAL_COMMANDS.md      1,158 tests
    README.md               1,158 tests  (Verifying the claims)
    README.md               1,149 tests  (Layout)
    docs/PRESENTATION.md    1,158 tests  (slide 2) and 1,149 (slide 4)
    docs/PRODUCTION-ROADMAP 1,152 progress marks
    slides_content.md       1,010 tests, and "329 canonical paths"

Not one of them was right, and two disagreed inside the same file. Every other
published figure in this project is regenerated by `scripts/bench/run_all.py` and
asserted by `tests/test_metrics_are_current.py`; these two were the numbers about
the repository itself, which is exactly the class nobody thinks to automate.

**Why `collected` and not `passed`.** A count of passing tests is a property of
the machine, not of the repository: `test_run_all_check_passes` is marked slow,
`test_the_real_bundle_indexes_and_reports_its_release` skips without a 53 MB
gitignored artifact, and a fresh clone therefore reports a smaller number than
this one does. Collection is deterministic — it depends on the files, not on what
is installed — so it is the figure that can be published without a footnote.

The trade this makes is deliberate: adding a test now fails the suite until the
documents are updated. That is the same bargain
`test_the_published_fixture_table_is_not_stale` already makes, and the reason is
the same. A number nothing checks is a number that is wrong and looks fine.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = PROJECT_ROOT.parent

#: Documents that state a count as a *fact about this repository*.
#:
#: ``docs/SCRIPT.md`` is deliberately absent: it quotes 1,010 because that is
#: what the frozen slide *image* says, and its whole job is to warn the presenter
#: that the image and the repository disagree. Rewriting that number would delete
#: the warning. Its own claim about the current count is pinned separately below.
PUBLISHING_DOCS = (
    PROJECT_ROOT / "README.md",
    PROJECT_ROOT / "docs" / "PRESENTATION.md",
    PROJECT_ROOT / "docs" / "ARCHITECTURE.md",
    PROJECT_ROOT / "docs" / "PRODUCTION-ROADMAP.md",
    PROJECT_ROOT / "guide.md",
    PROJECT_ROOT / "MANUAL_COMMANDS.md",
    WORKSPACE_ROOT / "slides_content.md",
)

#: Tolerant of ``**1,158** tests`` as well as ``1,158 tests``, because markdown
#: emphasis is what let one of the six stale figures hide from a plain grep.
#:
#: Backticks and a table-cell pipe are tolerated for the same reason, one rot
#: later: the slide deck states its headline figure as ``| `1,648` | tests green``
#: — a two-column KPI row, figure in one cell and noun in the next. That form was
#: invisible here, so while five figures on the same deck were swept to the
#: current count this one stayed behind and the submission document carried two
#: different test counts. Emphasis, code-span and cell-boundary are all just
#: punctuation between a number and its noun; none of them changes the claim.
_COUNT_RE = re.compile(r"[`*]{0,2}(\d[\d,]{2,7})[`*]{0,2}\s*\|?\s+(?:tests|progress marks)\b")

#: A figure whose noun sits on the line *below* it, in the same column.
#:
#: Slide 4's KPI strip is drawn as an ASCII mockup — a row of big figures, then a
#: row of labels underneath, aligned by column:
#:
#: .. code-block:: text
#:
#:     │   1,648        3,366           98.5%   │
#:     │   tests green  controls        parsed  │
#:
#: ``_COUNT_RE`` is deliberately line-scoped, because a marker or a noun that
#: could reach across lines would let one figure silently exempt its neighbour.
#: That same scoping makes the mockup unreadable to it. The column *is* the
#: pairing the mockup uses, so reading the column is not a heuristic about
#: nearby text — it is the document's own layout, and it costs nothing to honour.
_FIGURE_RE = re.compile(r"\d[\d,]{2,7}")

#: ``330 canonical paths``, ``330 dotted paths``, ``330 paths``, ``330-path``.
#:
#: The hyphenated form was invisible to the first version of this pattern, which
#: required whitespace before the noun. Four live figures were written that way
#: (``the 331-path schema``, ``the 331-path fact vocabulary``) and none of them
#: was gated — the count happened to be right, so the hole stayed open until an
#: ADR was found three revisions behind at ``329-path``.
_PATHS_RE = re.compile(
    r"\*{0,2}(\d{3})\*{0,2}(?:\s+(?:canonical |dotted )?paths\b|-path\b)"
)

#: ``25 endpoints``, ``25 REST endpoints``, ``25 routes``.
_ENDPOINTS_RE = re.compile(r"\*{0,2}(\d{1,3})\*{0,2}\s+(?:REST\s+)?(?:endpoints|routes)\b")

#: ``the repo is currently at **1,149 tests**`` in docs/SCRIPT.md.
_SCRIPT_CURRENT_RE = re.compile(r"currently\s*\n?at\s+\*{0,2}(\d[\d,]{2,7})\*{0,2}\s+tests")

#: Opt-out for a figure that is *deliberately* historical.
#:
#: §7 of the roadmap is a verification register: "on 2026-09-07 this command
#: printed 1,152 progress marks and exited 0". Rewriting that to today's count
#: would not fix a stale number, it would falsify a record of what was actually
#: observed — which is a worse failure than the one this module exists to catch.
#: So the exemption is explicit and visible in the source line, rather than a
#: heuristic about nearby dates that would quietly widen over time.
FROZEN_MARKER = "<!-- as-measured -->"

#: Declares that a count describes *part* of the suite, and which part.
#:
#: ``_COUNT_RE`` cannot tell "1,389 tests" (the whole suite) from "131 tests"
#: (two files), and both claims rot in exactly the same way. FROZEN_MARKER is the
#: wrong tool for the second kind: these are not dated records of a past run,
#: they are live claims that happen to be scoped, and exempting them outright
#: would mean the two most specific figures in the documentation are the only two
#: nothing checks.
#:
#: So the marker carries its scope, and
#: :func:`test_every_scoped_test_count_is_current` re-collects precisely those
#: files and compares. Paths are whitespace-separated and relative to
#: ``praman/``.
SCOPED_RE = re.compile(r"<!--\s*scoped:\s*([^>]+?)\s*-->")


def _as_int(literal: str) -> int:
    return int(literal.replace(",", ""))


def _grouped(value: int) -> str:
    return f"{value:,}"


def _collect(targets: tuple[str, ...] = ()) -> tuple[int | None, str]:
    """Ask pytest how many tests it collects, for the whole suite or named files.

    A subprocess rather than an in-process ``pytest.main``: collecting the suite
    from inside the suite mutates the running session's own state, and the failure
    that produces is confusing enough to be worse than the drift it was added to
    catch.

    Returns ``(count, diagnostic)``; ``count`` is ``None`` when pytest's output
    carried no total line, in which case the diagnostic is what to print.
    """
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            "--collect-only",
            # `-o addopts=` clears the `-q` that pyproject.toml already supplies.
            # Without it this inherits that `-q`, becomes `-qq`, and pytest switches
            # to a per-file summary with no total line at all — a silent format
            # change that looks like a broken subprocess.
            "-o",
            "addopts=",
            "-q",
            "-p",
            "no:cacheprovider",
            *targets,
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    match = re.search(r"(\d+)\s+tests?\s+collected", proc.stdout)
    if match is None:
        return None, (
            "could not read a collection count out of pytest's own output for "
            f"{list(targets) or 'the whole suite'}. exit={proc.returncode}\n"
            f"stdout tail:\n{proc.stdout[-2000:]}\nstderr tail:\n{proc.stderr[-2000:]}"
        )
    return int(match.group(1)), ""


@pytest.fixture(scope="module")
def collected_tests() -> int:
    """How many tests this repository declares, asked of pytest itself."""
    count, diagnostic = _collect()
    if count is None:  # pragma: no cover
        pytest.fail(diagnostic)
    return count


def _claims(pattern: re.Pattern[str], path: Path) -> list[tuple[int, int]]:
    """Every ``(line_number, value)`` in `path` matching `pattern`.

    Lines carrying `FROZEN_MARKER` or a `SCOPED_RE` marker are skipped. Both
    markers have to sit on the same physical line as the figure they cover, which
    is worth stating in the failure message: prose in these documents is
    hard-wrapped at ~80 columns, so an author who writes the marker after the
    sentence rather than after the number will land it on the next line and get an
    exemption that does nothing. The alternative — letting a marker cover its
    neighbours — would let one historical figure silently exempt a live one beside
    it. The same coarseness cuts the other way: a line carrying both a scoped
    figure and a whole-suite figure exempts both, so keep them on separate lines.
    """
    if not path.is_file():  # pragma: no cover
        return []
    found = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if FROZEN_MARKER in line or SCOPED_RE.search(line):
            continue
        for match in pattern.finditer(line):
            found.append((lineno, _as_int(match.group(1))))
    return found


def _column_paired_counts(path: Path) -> list[tuple[int, int]]:
    """Every ``(line_number, value)`` figure drawn directly above a 'tests' label.

    Same-column, not merely nearby: see :data:`_FIGURE_RE`. The frozen and scoped
    markers are honoured on the figure's own line, so a dated mockup can be
    exempted the same way any other historical figure is.
    """
    if not path.is_file():  # pragma: no cover
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    found = []
    for index, line in enumerate(lines[:-1]):
        if FROZEN_MARKER in line or SCOPED_RE.search(line):
            continue
        for label in re.finditer(r"\btests\b", lines[index + 1]):
            for figure in _FIGURE_RE.finditer(line):
                if abs(figure.start() - label.start()) <= 1:
                    found.append((index + 1, _as_int(figure.group())))
    return found


def _scoped_claims(path: Path) -> list[tuple[int, int, tuple[str, ...]]]:
    """Every ``(line_number, value, files)`` scoped claim in `path`."""
    if not path.is_file():  # pragma: no cover
        return []
    found = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        scope = SCOPED_RE.search(line)
        if scope is None:
            continue
        files = tuple(part for part in scope.group(1).split() if part)
        for literal in _COUNT_RE.findall(line):
            found.append((lineno, _as_int(literal), files))
    return found


def test_every_published_test_count_is_current(collected_tests: int) -> None:
    """One number, seven documents, and no way for them to disagree silently."""
    stale = [
        f"  {path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno} says "
        f"{_grouped(value)}"
        for path in PUBLISHING_DOCS
        for lineno, value in _claims(_COUNT_RE, path)
        if value != collected_tests
    ]
    assert not stale, (
        f"pytest collects {_grouped(collected_tests)} tests. These say otherwise:\n"
        + "\n".join(stale)
        + "\n\nUpdate them to "
        + _grouped(collected_tests)
        + f". If a figure is deliberately historical — a dated record of one run — "
        f"put `{FROZEN_MARKER}` on the same line as the number, not at the end of "
        "the sentence, and say what it is a record of. A bare stale figure reads "
        "as a current measurement."
    )


def test_every_column_paired_test_count_is_current(collected_tests: int) -> None:
    """A figure drawn above its label is still a published figure.

    Slide 4 of the deck leads with a KPI strip, and the biggest number on it is
    the test count. It is drawn in an ASCII mockup with the label on the next
    line, so the line-scoped :data:`_COUNT_RE` never saw it: five figures on that
    deck were swept to the current count and this one was not, which left the
    submission document asserting two different totals about itself — the exact
    disagreement this module exists to make impossible.

    The pairing is read by column rather than by proximity. "The number above the
    word" would also match a figure two paragraphs up in a hard-wrapped list; the
    mockup aligns figure to label deliberately, and matching that alignment is
    both stricter and closer to what the document means.
    """
    stale = [
        f"  {path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno} shows "
        f"{_grouped(value)} above its 'tests' label"
        for path in PUBLISHING_DOCS
        for lineno, value in _column_paired_counts(path)
        if value != collected_tests
    ]
    assert not stale, (
        f"pytest collects {_grouped(collected_tests)} tests. These figures sit "
        f"directly above a 'tests' label and disagree:\n"
        + "\n".join(stale)
        + f"\n\nUpdate them to {_grouped(collected_tests)}. These are drawn in "
        "fixed-width mockups, so keep the column width identical or the box "
        "stops lining up."
    )


def test_every_scoped_test_count_is_current() -> None:
    """A count of *some* of the tests is still a published count.

    Two documents quote a figure for a named subset — Step 14 of
    ``MANUAL_COMMANDS.md`` says the two export test modules hold 131 tests, and
    the roadmap's §5.3 block says the three of them hold 148. Both are the most
    specific test claims in the documentation, and before this test existed they
    were the only ones nothing re-derived: ``_COUNT_RE`` reads them as
    whole-suite claims and would have demanded they be rewritten to 1,389, which
    is how a true statement gets replaced by a false one to make a gate go green.

    So the exemption carries its scope and this test spends the subprocess to
    check it. The cost is one ``--collect-only`` per claim; the alternative was
    two numbers that drift the moment anyone adds an export test.
    """
    claims = [
        (path, lineno, value, files)
        for path in PUBLISHING_DOCS
        for lineno, value, files in _scoped_claims(path)
    ]
    assert claims, (
        "no scoped claims found. If the last one was removed, delete SCOPED_RE "
        "and this test with it — a marker mechanism nothing uses is a hole "
        "waiting for a wrong number to be parked in."
    )

    stale = []
    for path, lineno, value, files in claims:
        where = f"  {path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno}"
        absent = [name for name in files if not (PROJECT_ROOT / name).is_file()]
        if absent:
            stale.append(f"{where} scopes {absent}, which do not exist under praman/")
            continue
        actual, diagnostic = _collect(files)
        if actual is None:  # pragma: no cover
            stale.append(f"{where} {diagnostic}")
        elif actual != value:
            stale.append(
                f"{where} says {_grouped(value)}; those {len(files)} file(s) "
                f"collect {_grouped(actual)}"
            )
    assert not stale, "scoped test counts have drifted:\n" + "\n".join(stale)


def test_every_published_canonical_path_count_is_current() -> None:
    """`330` is the contract both the parsers and the rules are tested against.

    Published as "the 330 paths are the contract" in ARCHITECTURE.md and as a
    slide chip. It moved to 330 and two slide references stayed at 329, which is
    the kind of error a reader cannot catch and a grader might.

    Scanned wider than ``PUBLISHING_DOCS``. The path count is the one figure in
    this repository that is quoted as a *definition* rather than as a result —
    "the vocabulary is N paths" — so it turns up in the demo script, the
    presenter notes and the ADRs, none of which are marketing documents that a
    reader would discount. All three ADR references were found at ``329`` while
    every gated document read ``331``; ADR 0003's is a live recommendation about
    what a future decoder should be bounded to, and the ADR index is a live
    index, so neither is the kind of historical record ``FROZEN_MARKER`` exists
    to protect.
    """
    from backend.canonical.paths import canonical_paths

    actual = len(canonical_paths())
    documents = (
        *PUBLISHING_DOCS,
        PROJECT_ROOT / "docs" / "SCRIPT.md",
        PROJECT_ROOT / "docs" / "DEMO.md",
        *sorted((PROJECT_ROOT / "docs" / "adr").glob("*.md")),
    )
    stale = [
        f"  {path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno} says {value}"
        for path in documents
        for lineno, value in _claims(_PATHS_RE, path)
        if value != actual
    ]
    assert not stale, (
        f"the schema declares {actual} canonical paths. These say otherwise:\n"
        + "\n".join(stale)
    )


def test_every_published_endpoint_count_is_current() -> None:
    """The API surface is a published figure too, and it had already drifted.

    ``docs/SCRIPT.md`` said *"one FastAPI process: it serves 20 REST endpoints"*
    eight lines above a table headed *"25 endpoints across seven groups"* — the
    table was updated when the export router landed and the sentence was not.
    Nothing caught it, because unlike the test count and the path count this one
    had no gate. A presenter reading the deep-dive answer aloud would have
    contradicted their own table.

    ``SCRIPT.md`` is scanned here even though it is out of ``PUBLISHING_DOCS``:
    that exclusion exists for the frozen slide's test count, and extending it to
    every figure in the file would exempt the document that makes the most
    specific claims about the API.

    The denominator is ``app.openapi()`` rather than ``app.routes``, and
    deliberately: it counts what PRAMAN *documents*, which is the number a
    reader of these docs is checking. FastAPI's own ``/docs``, ``/redoc``,
    ``/openapi.json`` and the static mounts are not part of the claim.
    """
    from backend.app.main import app

    framework_owned = {"/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"}
    actual = len(set(app.openapi()["paths"]) - framework_owned)

    documents = (*PUBLISHING_DOCS, PROJECT_ROOT / "docs" / "SCRIPT.md")
    stale = [
        f"  {path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno} says {value}"
        for path in documents
        for lineno, value in _claims(_ENDPOINTS_RE, path)
        if value != actual
    ]
    assert not stale, (
        f"the app documents {actual} endpoints. These say otherwise:\n" + "\n".join(stale)
    )


def test_the_presenter_script_knows_the_current_test_count(collected_tests: int) -> None:
    """`docs/SCRIPT.md` warns the presenter that the slide graphic is stale.

    That warning is only useful if its *own* idea of the current count is right.
    A script that says "the slide says 1,010 but the repo is at 1,149" while the
    repo is at 1,237 sends the presenter on stage with a third wrong number,
    which is worse than either of the first two.

    The 1,010 in that file is left alone on purpose — see PUBLISHING_DOCS.
    """
    script = PROJECT_ROOT / "docs" / "SCRIPT.md"
    if not script.is_file():  # pragma: no cover
        pytest.skip("docs/SCRIPT.md is absent")

    match = _SCRIPT_CURRENT_RE.search(script.read_text(encoding="utf-8"))
    assert match is not None, (
        "docs/SCRIPT.md no longer states the current test count. It exists to "
        "reconcile the frozen slide graphic with the repository; without a "
        "current figure it cannot."
    )
    assert _as_int(match.group(1)) == collected_tests, (
        f"docs/SCRIPT.md calls the current count {match.group(1)}; pytest collects "
        f"{_grouped(collected_tests)}."
    )
