"""Test: a benchmark figure quoted in a deliverable must match the file it came from.

There are three relationships a measured number can be wrong in, and this project
had gates for two of them:

* **measurement → reality.** ``tests/test_metrics_are_current.py`` re-runs every
  benchmark in a subprocess and diffs the result against ``reports/metrics/*.json``.
  It proves the JSON is current. It does not open the slide deck.
* **document → repository.** ``tests/test_published_counts.py`` reads the README,
  the decks, the script and the guide, and re-derives what they claim about the
  repository itself — test count, endpoint count, canonical-path count.

The third edge, **document → measurement**, had nothing on it. So the README, the
technical deck and the idea-round deck all said the ReportLab-less fallback
renderer was "61.6× faster" while ``reports/metrics/pdf_generation.json``, freshly
regenerated by ``scripts/bench/run_all.py``, recorded **72.1×**. The JSON was
right, the three graded deliverables were wrong, and every test was green —
because each existing gate covered one end of the wire and neither covered the
wire.

This module is that edge. It is deliberately a separate file rather than a seventh
test in ``test_published_counts.py``: that module's subject is facts about the
repository, which are derived by asking Python and pytest about themselves, and
this one's subject is figures produced by a benchmark run. The two rot for
different reasons and are fixed by different commands — one by editing a
document, the other by re-running ``scripts/bench/run_all.py`` — and the failure
message has to say which.

**No literal lives here.** Every expected value is read out of the metrics file at
run time. Restating ``72.1`` in this module would create a second place for the
number to go stale, which is precisely the defect the module exists to catch.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = PROJECT_ROOT.parent

#: Documents that quote a benchmark ratio as a live claim to a reader.
#:
#: ``docs/PRODUCTION-ROADMAP.md`` is deliberately absent. It is a working log, and
#: §3.4 of it records *"156 ms → 22.5 ms per config, a 6.9x speedup"* about an
#: unrelated parse-cache fix — a dated record of one optimisation, not a headline
#: figure anyone is asked to trust. Scanning it would force this gate to tell two
#: benchmarks apart, and it cannot; see :func:`test_only_one_speedup_claim_exists`.
PUBLISHING_DOCS = (
    PROJECT_ROOT / "README.md",
    PROJECT_ROOT / "docs" / "PRESENTATION.md",
    PROJECT_ROOT / "docs" / "IDEA_ROUND_DECK.md",
    PROJECT_ROOT / "docs" / "ARCHITECTURE.md",
    PROJECT_ROOT / "docs" / "SCRIPT.md",
    PROJECT_ROOT / "docs" / "DEMO.md",
    WORKSPACE_ROOT / "slides_content.md",
)

#: ``**72.1× faster**``, ``72.1x faster``, ``72.1 × faster``.
#:
#: Anchored on the word *faster* and a decimal point. "Any number followed by an
#: x" would swallow version strings, and requiring the multiplication sign would
#: miss an author who typed the ASCII letter.
_SPEEDUP_RE = re.compile(r"\*{0,2}(\d+\.\d+)\*{0,2}\s*[×x]\s*faster\b")

#: Same opt-out grammar as ``test_published_counts.py``: on the figure's own line.
FROZEN_MARKER = "<!-- as-measured -->"

METRICS = PROJECT_ROOT / "reports" / "metrics" / "pdf_generation.json"


def _claims() -> list[tuple[Path, int, str]]:
    """Every ``(path, line_number, literal)`` speedup ratio published to a reader."""
    found = []
    for path in PUBLISHING_DOCS:
        if not path.is_file():  # pragma: no cover
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if FROZEN_MARKER in line:
                continue
            for match in _SPEEDUP_RE.finditer(line):
                found.append((path, lineno, match.group(1)))
    return found


def _where(path: Path, lineno: int) -> str:
    return f"{path.relative_to(WORKSPACE_ROOT).as_posix()}:{lineno}"


@pytest.fixture(scope="module")
def measured_speedup() -> float:
    """The fallback renderer's speedup, as the benchmark recorded it."""
    if not METRICS.is_file():  # pragma: no cover
        pytest.skip("reports/metrics/pdf_generation.json is absent")
    results = json.loads(METRICS.read_text(encoding="utf-8"))["results"]
    return float(results["fallback_renderer"]["speedup_vs_reportlab"])


def test_the_claim_still_exists() -> None:
    """A gate with nothing left to check is a hole, not a pass.

    If the fallback claim is ever dropped from every document, this module stops
    testing anything while continuing to report success — so the absence is made
    a failure, with instructions for the two legitimate cases.
    """
    assert _claims(), (
        "no document states an 'N× faster' ratio any more. If the fallback claim "
        "was removed on purpose, delete this module. If it was reworded, widen "
        f"_SPEEDUP_RE — currently {_SPEEDUP_RE.pattern!r}. Do not leave this test "
        "passing on an empty scan."
    )


def test_every_published_speedup_matches_the_measurement(measured_speedup: float) -> None:
    """One ratio, three deliverables, and no way for them to drift unnoticed."""
    stale = [
        f"  {_where(path, lineno)} says {literal}×"
        for path, lineno, literal in _claims()
        if float(literal) != measured_speedup
    ]
    assert not stale, (
        f"{METRICS.relative_to(PROJECT_ROOT).as_posix()} measures the fallback "
        f"renderer at {measured_speedup}× faster. These disagree:\n"
        + "\n".join(stale)
        + "\n\nIf the *measurement* moved, re-run `python scripts/bench/run_all.py` "
        "and then sweep the documents. If only the documents are behind, update "
        f"them to {measured_speedup}×. Never edit the JSON to match a document — "
        "it is generated, and the next benchmark run would overwrite the edit "
        "while the document kept the wrong number."
    )


def test_only_one_speedup_claim_exists() -> None:
    """The pattern keys on a phrase, not on a subject, so ambiguity must be fatal.

    ``_SPEEDUP_RE`` finds *"N× faster"*. It has no way to know what was made
    faster. That is fine while the PDF fallback is the only thing these documents
    describe that way, and quietly wrong the moment a second ratio appears —
    the new claim would be held to the PDF benchmark's value, and an author could
    "fix" a correct number to make this suite go green.

    So a second distinct ratio fails here, loudly, with the remedy: give it its
    own assertion against its own metrics file. The check is on *distinct values*
    rather than on occurrence count, because the same figure repeated across three
    decks is the normal case and is exactly what the module above is for.
    """
    claims = _claims()
    distinct = sorted({literal for _, _, literal in claims})
    assert len(distinct) <= 1, (
        f"{len(distinct)} distinct speedup ratios are published across these "
        f"documents: {distinct}\n"
        + "\n".join(f"  {_where(path, lineno)} says {literal}×" for path, lineno, literal in claims)
        + "\n\nThis module can only verify one, and it verifies it against "
        "pdf_generation.json. Add an assertion for the other ratio against the "
        "metrics file it came from, then widen this test. Do not rewrite a correct "
        "figure to make one gate pass."
    )
