"""AI Escalation Ladder — Tier 2: SetFit few-shot classifier.

SetFit 1.1.3 over sentence-transformers/all-MiniLM-L6-v2 (384-dim, 22.7M params).
Config lines are far shorter than the 256 word-piece cap — no truncation risk.

SPINE §18.1: Runs when Tier 1 confidence < tau_tfidf.

Trained by ``scripts/train_setfit.py`` (MANUAL_COMMANDS.md Step 8c). Read
``OOD_SIMILARITY_FLOOR`` before changing anything here: this tier is measurably
overconfident on input outside its label set, and the guard is what stops that
overconfidence reaching an operator.
"""

from __future__ import annotations

import logging
from typing import Any

from backend.app.config import MODELS_DIR, SENTINEL_AI_BACKEND, TAU_SETFIT
from backend.core_errors import ArtifactMissingError

logger = logging.getLogger(__name__)

SETFIT_MODEL_PATH = MODELS_DIR / "classifier" / "setfit_model"

#: Nearest-neighbour reference set written beside the model by the trainer.
NEIGHBOUR_INDEX_PATH = SETFIT_MODEL_PATH / "neighbour_index.npz"

#: How similar a line must be to the nearest *training* example of the class the
#: head picked before that prediction is treated as a reading of the line.
#:
#: This is the tier-2 analogue of ``PRIOR_EVIDENCE_MARGIN`` in ``tfidf_clf.py``,
#: and it exists for the same reason: a measured defect, not a hypothetical one.
#: The mechanism is different because tier 2 fails differently. Tier 1 collapsed to
#: a flat 0.93 for everything, so distance-from-prior detected it. Tier 2's prior is
#: genuinely flat (0.1947 on the empty string, over 14 classes), so there is no
#: prior to be near — and yet it is *more* wrong. Measured on the shipped artefact:
#:
#:     "no passive-interface GigabitEthernet0/0" -> interface.admin_state  0.9935
#:     "passive-interface default"               -> interface.admin_state  0.9927
#:     "switchport trunk encapsulation dot1q"    -> interface.admin_state  0.9455
#:     '{"framework": "CIS", "result": "pass"}'  -> interface.admin_state  0.9249
#:     "hostname CORE-RTR-01"                    -> device.hostname        0.9171
#:     "shutdown"                                -> interface.admin_state  0.1552
#:
#: Four confident answers that are wrong, one that is right, and the single most
#: canonical ``interface.admin_state`` command in IOS scoring lowest of all. The
#: head's probability is not ordered by correctness, so no value of TAU_SETFIT
#: makes this tier net-positive; that was measured across a grid of thresholds and
#: the best cell still answered two lines wrong for three right.
#:
#: The cause is inherited, not a training bug. Labels are generated by the
#: deterministic parsers (``train_classifier.py:_generate_labels_from_corpus``), so
#: ``interface.admin_state`` is overwhelmingly Junos ``set interfaces`` stanzas —
#: and ``no passive-interface GigabitEthernet0/0`` really is nearly identical to
#: those, at 0.9836 cosine. The embedding is not malfunctioning. It is being asked
#: a closed-set question about a line whose correct path is one of the 316 the model
#: was never given, and a 14-way head has no way to answer "none of these".
#:
#: 0.99 is not a round number chosen for comfort. It is the highest-recall floor
#: that admits zero wrong answers on a hand-labelled probe set, swept:
#:
#:     floor   right  wrong
#:     0.850     4      2
#:     0.900     3      2
#:     0.970     3      1
#:     0.980     2      1
#:     0.985     2      0     <- zero false positives first reached here
#:     0.990     2      0     <- same recall, wider margin: chosen
#:     0.999     1      0
#:
#: 0.985 and 0.99 have identical recall, so the tighter one is free safety: the
#: highest false positive observed is ``no passive-interface GigabitEthernet0/0``
#: at 0.9836, and 0.99 clears it by 0.0064 rather than 0.0014.
#:
#: Be honest about what this leaves. At 0.99 the tier fires only on near-exact
#: duplicates of lines it was trained on — ``service timestamps log datetime msec``
#: passes at 1.0000 because it is literally in the training set. That is a
#: memorised lookup, not few-shot generalisation, and it is worth having only
#: because estates repeat the same commands across hundreds of devices. The tier
#: cannot do the job SetFit was chosen for until it has a reject class trained on
#: the unparsed residue, which is recorded in docs/GAPS.md as the real fix.
OOD_SIMILARITY_FLOOR = 0.99


class SetFitClassifier:
    """Tier 2 — SetFit few-shot classifier.

    Never emits confidence = 1.0 (SPINE), and never emits a path for a line that
    is unlike anything it was trained on (see ``OOD_SIMILARITY_FLOOR``).
    """

    def __init__(self) -> None:
        self._model: Any = None
        self._index: Any = None
        self._index_labels: Any = None

    def is_available(self) -> bool:
        if SENTINEL_AI_BACKEND == "none":
            return False
        return SETFIT_MODEL_PATH.exists()

    def load(self) -> None:
        if not self.is_available():
            raise ArtifactMissingError(
                f"SetFit model not found at {SETFIT_MODEL_PATH}. "
                "Run Step 8c in MANUAL_COMMANDS.md (scripts/train_setfit.py) to "
                "train it. Step 8a trains Tier 1 only and does not write this path."
            )
        try:
            from setfit import SetFitModel
            self._model = SetFitModel.from_pretrained(str(SETFIT_MODEL_PATH))
        except ImportError as err:
            raise ArtifactMissingError(
                "setfit and sentence-transformers are required and are not in "
                "requirements.lock.txt — Step 1 does not install them. Run Step "
                "8c in MANUAL_COMMANDS.md, which pins the exact versions that "
                "produced the shipped artefact."
            ) from err

        self._load_neighbour_index()

    def _load_neighbour_index(self) -> None:
        """Load the OOD reference set, or fail closed if it is absent.

        A missing index is not treated as "guard disabled". An unguarded tier 2
        answers nonsense at 0.92, so degrading to unguarded on a missing file would
        make a packaging slip look like a working feature — the exact failure this
        module already had once, in the other direction.
        """
        if not NEIGHBOUR_INDEX_PATH.exists():
            logger.warning(
                "Tier 2 neighbour index missing at %s — the out-of-distribution "
                "guard cannot run, so this tier will abstain on everything. "
                "Rebuild it with scripts/train_setfit.py (Step 8c).",
                NEIGHBOUR_INDEX_PATH,
            )
            self._index = None
            return
        import numpy as np

        with np.load(NEIGHBOUR_INDEX_PATH, allow_pickle=True) as payload:
            self._index = payload["embeddings"]
            self._index_labels = [str(x) for x in payload["labels"]]
        logger.debug(
            "Tier 2 neighbour index: %d examples over %d classes",
            len(self._index_labels),
            len(set(self._index_labels)),
        )

    def predict(self, line: str) -> tuple[str, float]:
        """Predict the canonical path for a config line.

        Returns:
            ``(predicted_path, confidence)`` where confidence is always < 1.0, or
            ``("", 0.0)`` when the line is unlike anything the model was trained on.
            The path is blanked rather than returned with a low score, matching
            tier 1: a plausible path callers must remember not to trust is the shape
            of the bug, and an empty path fails ``is_canonical_path`` loudly.
        """
        if self._model is None:
            self.load()

        predictions = self._model.predict([line])
        proba = self._model.predict_proba([line])
        max_conf = float(proba[0].max())
        # Clamp to < 1.0 — only Tier 0 may emit 1.0.
        max_conf = min(max_conf, 0.999)
        predicted_path = str(predictions[0])

        if self._index is None:
            return "", 0.0

        similarity = self._nearest_similarity(line, predicted_path)
        if similarity < OOD_SIMILARITY_FLOOR:
            logger.debug(
                "Tier 2 out-of-distribution on %r: %s at %.3f but only %.3f cosine "
                "to the nearest %s training example — abstaining rather than "
                "suggesting a class the line only resembles",
                line[:80],
                predicted_path,
                max_conf,
                similarity,
                predicted_path,
            )
            return "", 0.0

        return predicted_path, max_conf

    def _nearest_similarity(self, line: str, predicted_path: str) -> float:
        """Cosine similarity to the closest training example *of the predicted class*.

        Scoped to the predicted class rather than the whole index on purpose. The
        question the guard has to answer is "does this line look like the thing you
        are about to call it", and the nearest neighbour overall can belong to a
        different class — measured: ``shutdown``'s nearest neighbour is a
        ``line.console.exec_timeout`` example. Answering the global question would
        admit a line on the strength of its resemblance to something the model did
        not predict.
        """
        import numpy as np

        mask = [i for i, label in enumerate(self._index_labels) if label == predicted_path]
        if not mask:
            # The head can emit a label the index has no rows for only if the two
            # artefacts came from different runs. Abstain rather than guess.
            logger.warning(
                "Tier 2 predicted %r but the neighbour index has no examples of it; "
                "model and index are out of sync",
                predicted_path,
            )
            return 0.0

        query = np.asarray(
            self._model.model_body.encode([line], normalize_embeddings=True),
            dtype="float32",
        )[0]
        return float(np.max(self._index[mask] @ query))

    def confidence_threshold(self) -> float:
        return TAU_SETFIT
