"""AI Escalation Ladder — Tier 1: TF-IDF char-ngram classifier.

Uses scikit-learn TfidfVectorizer with character n-grams (analyzer="char_wb")
because config CLI tokens (interface names, ACL numbers, snmp-server community)
are sub-word. LogisticRegression is well-calibrated by itself.

SPINE §18.1: Runs when Tier 0 (deterministic parse) left the line unparsed.

The claim in the line above — "LogisticRegression is well-calibrated by itself" —
is true for in-distribution input and false for the input this tier actually
receives. A calibrated softmax reports P(class | it is one of my classes); it has
no way to say "this is not a config line at all". On a class-imbalanced 15-class
model that turns into a confident constant answer for arbitrary text. See
``PRIOR_EVIDENCE_MARGIN`` for the measurements and the guard added because of them.
"""

from __future__ import annotations

import logging
from typing import Any

from backend.app.config import MODELS_DIR, SENTINEL_AI_BACKEND, TAU_TFIDF
from backend.core_errors import ArtifactMissingError

logger = logging.getLogger(__name__)

# Model artifacts
TFIDF_MODEL_PATH = MODELS_DIR / "classifier" / "tfidf_pipeline.joblib"

#: How far a line must move the model off its *unconditional* prior before the
#: prediction is treated as evidence about that line.
#:
#: This exists because of a measured defect, not a hypothetical one. The shipped
#: model has 15 classes and is trained on labels auto-generated by the
#: deterministic parsers, so ``interface.admin_state`` — the most common fact in
#: any Cisco config — dominates the training set. The calibrated softmax learned
#: ``P(interface.admin_state) ≈ 0.93`` *unconditionally*, and since 0.93 clears
#: TAU_TFIDF (0.85), the escalation threshold never fired. Measured behaviour
#: before this guard:
#:
#:     "shutdown"            -> interface.admin_state  0.929
#:     "zzzzzzzz qqqq"       -> interface.admin_state  0.929
#:     "milk, eggs, bread"   -> interface.admin_state  0.928
#:     "The quick brown fox" -> interface.admin_state  0.897
#:
#: Those numbers are the point: the fallback class scores the same for a real
#: config command as for a shopping list, which means the probability is reporting
#: the class prior and nothing about the input. A confidence that does not vary
#: with the input is not a confidence. Left unguarded, the training queue offers an
#: operator ``interface.admin_state`` at "93% confidence" for arbitrary text, and
#: one approval writes that into the pattern library permanently.
#:
#: 0.05 is chosen to be comfortably larger than the spread actually observed on
#: out-of-distribution input (±0.03 of the prior) and small enough that a genuine
#: signal clears it. It is a threshold on a measured margin, not a tuned
#: hyperparameter — no held-out set exists to tune it against, which is stated in
#: reports/metrics/ai_abstention.json rather than hidden.
PRIOR_EVIDENCE_MARGIN = 0.05

#: The input used to read the model's unconditional prior. An empty string has no
#: character n-grams at all, so whatever the pipeline returns for it is the
#: distribution it falls back to in the absence of evidence.
_NEUTRAL_INPUT = ""


class TfidfClassifier:
    """Tier 1 — TF-IDF character n-gram classifier.

    Never emits confidence = 1.0 (SPINE: only deterministic parse does that), and
    never emits a path it inferred solely from the class prior (see
    ``PRIOR_EVIDENCE_MARGIN``).
    """

    def __init__(self) -> None:
        self._pipeline: Any = None
        self._prior: Any = None
        self._prior_class_index: int = -1

    def is_available(self) -> bool:
        """Check if the trained model is present."""
        if SENTINEL_AI_BACKEND == "none":
            return False
        return TFIDF_MODEL_PATH.exists()

    def load(self) -> None:
        """Load the trained pipeline from disk."""
        if not self.is_available():
            raise ArtifactMissingError(
                f"TF-IDF classifier not found at {TFIDF_MODEL_PATH}. "
                "Run Step 8a in MANUAL_COMMANDS.md to train it. Step 8c trains "
                "Tier 2 and does not write this path."
            )
        try:
            import joblib
            self._pipeline = joblib.load(str(TFIDF_MODEL_PATH))
        except ImportError as err:
            raise ArtifactMissingError(
                "joblib is required for loading the TF-IDF classifier. "
                "Install scikit-learn (Step 1 in MANUAL_COMMANDS.md)."
            ) from err

        # Read the prior once, here, rather than on every predict(): it is a
        # property of the model file and costs a vectorise plus a matrix multiply.
        self._prior = self._pipeline.predict_proba([_NEUTRAL_INPUT])[0]
        self._prior_class_index = int(self._prior.argmax())
        logger.debug(
            "Tier 1 prior: %s at %.4f over %d classes",
            self._pipeline.classes_[self._prior_class_index],
            self._prior[self._prior_class_index],
            len(self._pipeline.classes_),
        )

    def known_paths(self) -> list[str]:
        """The canonical paths this model can emit at all.

        Published by ``scripts/bench/bench_llm_abstention.py`` because it is the
        ceiling on tier 1's usefulness and it is not visible from anywhere else:
        the model is trained on labels the deterministic parsers generated, so it
        only ever learns paths that were already parseable. On the shipped
        artefact that is 15 of the 330 paths the schema publishes, which means
        tier 1 cannot suggest the right answer for the large majority of lines it
        will be asked about. Better stated than discovered.
        """
        if self._pipeline is None:
            self.load()
        return [str(c) for c in self._pipeline.classes_]

    def predict(self, line: str) -> tuple[str, float]:
        """Predict the canonical path for a config line.

        Returns:
            ``(predicted_path, confidence)`` where confidence is always < 1.0,
            or ``("", 0.0)`` when the prediction is the model's unconditional
            prior rather than a reading of ``line`` — see
            ``PRIOR_EVIDENCE_MARGIN``. The path is deliberately blanked in that
            case rather than returned alongside a low confidence: returning a
            plausible path that callers must remember not to trust is exactly the
            shape of the bug this guard fixes, and an empty path fails
            ``is_canonical_path`` loudly instead of silently.
        """
        if self._pipeline is None:
            self.load()

        proba = self._pipeline.predict_proba([line])[0]
        max_idx = int(proba.argmax())
        confidence = float(proba[max_idx])

        # Clamp to < 1.0 — only Tier 0 may emit 1.0
        confidence = min(confidence, 0.999)

        predicted_path = str(self._pipeline.classes_[max_idx])

        if max_idx == self._prior_class_index:
            evidence = confidence - float(self._prior[max_idx])
            if evidence < PRIOR_EVIDENCE_MARGIN:
                logger.debug(
                    "Tier 1 prior collapse on %r: %s at %.3f is only %+.3f off the "
                    "unconditional prior — abstaining rather than escalating a "
                    "class prior as a prediction",
                    line[:80],
                    predicted_path,
                    confidence,
                    evidence,
                )
                return "", 0.0

        return predicted_path, confidence

    def confidence_threshold(self) -> float:
        """Return the escalation threshold for this tier."""
        return TAU_TFIDF
