"""Regenerate the fixture expectations table in ``test_configs/README.md``.

Every number published about the shipped fixtures comes from here, so a claim in
the README can always be re-derived rather than trusted. Run it after changing a
fixture, a pattern pack or a mapping pack, and paste the markdown block it emits.

    python scripts/fixture_report.py            # markdown tables, to stdout
    python scripts/fixture_report.py --write     # rewrite the block in the README
    python scripts/fixture_report.py --check     # exit 1 if the README is stale
    python scripts/fixture_report.py --detail    # per-control results, one fixture

Offline and fast: no server, no models, no network. Frameworks are restricted to
the directly-evaluated set and governance projection is off, so the table shows
what the rules themselves decided rather than what a roll-up inferred.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.app.config import FILE_ENCODING, PROJECT_ROOT
from backend.canonical.findings import Result
from backend.ingest.generic import PatternAdapterRegistry
from backend.rules.evaluator import RulesEvaluator, compute_compliance_score
from scripts.bench.bench_parse_coverage import is_significant

CONFIG_DIR = PROJECT_ROOT / "test_configs"
README = CONFIG_DIR / "README.md"

#: Only the frameworks whose rules are evaluated against the canonical model.
#: Including the projected frameworks would double-count: NIST and ISO controls
#: are rolled up from these contributors, so their results are not independent
#: evidence about the fixture.
#:
#: This list must stay identical to ``DIRECT`` in tests/test_rules_mapping.py.
#: When it read ``["CIS"]`` while a second pack shipped, the published table and
#: the assertions behind it both quietly excluded the newest rules — the table
#: still looked complete, which is the failure mode this whole document exists
#: to prevent.
DIRECT_FRAMEWORKS = ["CIS", "DISA_STIG"]

#: The table lives between these markers so --check and a paste-in both work.
BEGIN = "<!-- BEGIN fixture-table (generated by scripts/fixture_report.py) -->"
END = "<!-- END fixture-table -->"


@dataclass(frozen=True)
class Parse:
    """What the pattern pack made of one fixture.

    Kept separate from :class:`Verdict` because parsing happens once and is a
    property of the fixture and the pattern pack alone. Repeating the fact count
    beside every framework's verdict would imply the two vary together.
    """

    path: str
    lines: int
    facts: int
    unparsed: int
    #: Of ``unparsed``, the ones that carry configuration. The two differ by an
    #: order of magnitude on a heavily-commented fixture, and publishing only
    #: the raw count makes a well-documented file look like a parser failure.
    unparsed_significant: int


@dataclass(frozen=True)
class Verdict:
    """One framework's decision about one fixture."""

    path: str
    framework: str
    score: float
    passed: int
    failed: int
    unknown: int
    notapplicable: int
    notchecked: int
    #: Of ``notchecked``, how many sit in a benchmark this project has mapped.
    #: Those are individually argued in docs/GAPS.md. The remainder belong to
    #: benchmarks with no mapping pack written yet, which is a roadmap item
    #: rather than a judgement about a control, and collapsing the two into one
    #: number would let a missing pack read as a considered decision.
    notchecked_in_mapped_benchmarks: int
    unmapped_benchmarks: int

    @property
    def is_pole(self) -> bool:
        """Whether this fixture's verdict is constrained by the test suite."""
        return self.path.startswith("compliance_extremes/")


def measure(
    config: Path, registry: PatternAdapterRegistry, evaluator: RulesEvaluator
) -> tuple[Parse, list[Verdict]]:
    """Parse one fixture once, then score it against each direct framework."""
    text = config.read_text(encoding=FILE_ENCODING)
    adapter = registry.detect(text, config.name)
    if adapter is None:
        raise SystemExit(
            f"no pattern pack detects {config.name}. A fixture for a new vendor "
            "needs data/ingest/patterns/<vendor>.yaml before it can be measured."
        )
    parsed = adapter.parse(text, config.name)
    path = config.relative_to(CONFIG_DIR).as_posix()

    verdicts = []
    for framework in DIRECT_FRAMEWORKS:
        findings = evaluator.evaluate(
            parsed.facts,
            adapter.pack.vendor,
            adapter.pack.os_family,
            frameworks=[framework],
            project_governance=False,
        )
        score = compute_compliance_score(findings)
        mapped = {f.benchmark for f in findings if f.result is not Result.NOTCHECKED}
        notchecked = [f for f in findings if f.result is Result.NOTCHECKED]
        verdicts.append(
            Verdict(
                path=path,
                framework=framework,
                score=score["score"],
                passed=score["passed"],
                failed=score["failed"],
                unknown=score["unknown"],
                notapplicable=score["notapplicable"],
                notchecked=score["notchecked"],
                notchecked_in_mapped_benchmarks=sum(
                    1 for f in notchecked if f.benchmark in mapped
                ),
                unmapped_benchmarks=len({f.benchmark for f in notchecked} - mapped),
            )
        )

    return (
        Parse(
            path=path,
            lines=len(text.splitlines()),
            facts=len(parsed.facts),
            unparsed=len(parsed.unparsed_lines),
            unparsed_significant=sum(
                1 for entry in parsed.unparsed_lines if is_significant(entry["raw_text"])
            ),
        ),
        verdicts,
    )


def measure_all() -> tuple[list[Parse], list[Verdict]]:
    registry, evaluator = PatternAdapterRegistry(), RulesEvaluator()
    configs = sorted(CONFIG_DIR.rglob("*.conf"))
    if not configs:
        raise SystemExit(f"no fixtures found under {CONFIG_DIR}")
    parses: list[Parse] = []
    verdicts: list[Verdict] = []
    for config in configs:
        parse, per_framework = measure(config, registry, evaluator)
        parses.append(parse)
        verdicts += per_framework
    return parses, verdicts


def render(parses: list[Parse], verdicts: list[Verdict]) -> str:
    """Render the two markdown tables the README publishes."""
    out = [
        BEGIN,
        "",
        "### Parsing",
        "",
        "One row per fixture: what the pattern pack extracted, before any rule ran.",
        "",
        "*Unparsed* splits into the lines that carry configuration and the ones that",
        "do not. Only the first column is a coverage claim: a fixture whose header",
        "explains why each control fails contributes dozens of unparsed comment lines",
        "and zero unparsed configuration. The published coverage figure in the project",
        "README counts the significant column only.",
        "",
        "| Fixture | Lines | Facts | Unparsed (config) | Unparsed (comments) |",
        "|---|--:|--:|--:|--:|",
    ]
    out += [
        f"| `{p.path}` | {p.lines} | {p.facts} | {p.unparsed_significant} "
        f"| {p.unparsed - p.unparsed_significant} |"
        for p in parses
    ]
    out += [
        "",
        f"{len(parses)} fixtures, {sum(p.facts for p in parses)} facts, "
        f"{sum(p.unparsed_significant for p in parses)} unparsed configuration lines "
        f"({sum(p.unparsed for p in parses)} unparsed lines in total, the remainder "
        f"being comments and separators).",
        "",
        "### Verdicts",
        "",
        f"One row per fixture per directly-evaluated framework "
        f"({', '.join(DIRECT_FRAMEWORKS)}), governance projection off, so each row "
        "is what that framework's own rules decided rather than what a roll-up "
        "inferred. **Bold** rows are the two poles, whose verdicts are constrained "
        "by `tests/test_rules_mapping.py`; the rest are observations.",
        "",
        "| Fixture | Framework | Score | pass | fail | unknown | n/a | notchecked |",
        "|---|---|--:|--:|--:|--:|--:|--:|",
    ]
    for v in verdicts:
        # "—" rather than "0.0%" when nothing was decided. The two are opposite
        # findings and the table is read by people who will quote a number out of
        # it: an Arista switch has no CIS benchmark, so its CIS row scores nothing,
        # and printing 0.0% there would publish a totally-non-compliant device
        # that does not exist. `score_from_counts` must return a float, so the
        # distinction has to be made where the value is rendered.
        if v.passed + v.failed == 0:
            score = "—"
        else:
            score = f"**{v.score}%**" if v.is_pole else f"{v.score}%"
        out.append(
            f"| `{v.path}` | {v.framework} | {score} | {v.passed} | {v.failed} "
            f"| {v.unknown} | {v.notapplicable} | {v.notchecked} |"
        )

    out += [
        "",
        f"{sum(v.passed + v.failed for v in verdicts)} automated results across "
        f"{len(DIRECT_FRAMEWORKS)} frameworks. Nothing is dropped: every control "
        "in scope for the device that no rule decided is returned as `notchecked`, "
        "which is what keeps the coverage figure honest.",
        "",
        "Splitting that `notchecked` column, because its two halves mean different "
        "things — a control argued in [`docs/GAPS.md`](../docs/GAPS.md) is a "
        "judgement, a benchmark with no mapping pack yet is a roadmap item, and "
        "one number covering both would let the second read as the first:",
        "",
        "| Framework | notchecked / fixture | in a mapped benchmark | in benchmarks with no pack yet |",
        "|---|--:|--:|--:|",
    ]
    for framework in DIRECT_FRAMEWORKS:
        rows = [v for v in verdicts if v.framework == framework]
        total = {v.notchecked for v in rows}
        argued = {v.notchecked_in_mapped_benchmarks for v in rows}
        packs = {v.unmapped_benchmarks for v in rows}
        # Constant across fixtures by construction: the catalog set in scope for a
        # vendor does not depend on how that vendor's device is configured. Shown
        # as a range rather than asserted, so a future vendor pack that breaks the
        # assumption changes the table instead of tripping over an assert here.
        out.append(
            f"| {framework} | {_span(total)} | {_span(argued)} | "
            f"{_span({v.notchecked - v.notchecked_in_mapped_benchmarks for v in rows})} "
            f"({_span(packs)} benchmarks) |"
        )
    out += ["", END]
    return "\n".join(out)


def _span(values: set[int]) -> str:
    """Render a set of per-fixture counts as one number, or a range if they vary."""
    return str(values.pop()) if len(values) == 1 else f"{min(values)}–{max(values)}"


def detail(fixture: str) -> int:
    """Print every control's result for one fixture, for diagnosing a row."""
    matches = [c for c in CONFIG_DIR.rglob("*.conf") if fixture in c.as_posix()]
    if len(matches) != 1:
        print(
            f"'{fixture}' matched {len(matches)} fixtures; "
            f"be more specific. Available:\n  "
            + "\n  ".join(
                sorted(c.relative_to(CONFIG_DIR).as_posix() for c in CONFIG_DIR.rglob("*.conf"))
            ),
            file=sys.stderr,
        )
        return 1

    config = matches[0]
    registry, evaluator = PatternAdapterRegistry(), RulesEvaluator()
    text = config.read_text(encoding=FILE_ENCODING)
    adapter = registry.detect(text, config.name)
    parsed = adapter.parse(text, config.name)
    findings = evaluator.evaluate(
        parsed.facts,
        adapter.pack.vendor,
        adapter.pack.os_family,
        frameworks=DIRECT_FRAMEWORKS,
        project_governance=False,
    )

    print(f"{config.relative_to(CONFIG_DIR).as_posix()}  ({adapter.pack.vendor})\n")
    for f in findings:
        if f.result is Result.NOTCHECKED:
            continue
        print(
            f"  {f.result.value:<14} {f.severity or '-':<8} {f.framework:<11} "
            f"{f.control_id:<12} {f.title[:52]}"
        )

    unmapped = [f.control_id for f in findings if f.result is Result.NOTCHECKED]
    print(f"\n  notchecked ({len(unmapped)}): {', '.join(unmapped)}")

    if parsed.unparsed_lines:
        print(f"\n  unparsed lines ({len(parsed.unparsed_lines)}):")
        for line in parsed.unparsed_lines:
            # An unparsed line is a dict carrying its own provenance, so the
            # line number is printed alongside the text: an unparsed line you
            # cannot locate in the source file is not actionable, and locating
            # them is the whole point of feeding them to the Training GUI.
            number = line.get("line_number", "?")
            block = line.get("block") or ""
            where = f" [in {block}]" if block else ""
            print(f"  {number:>5}: {line.get('raw_text', '').strip()[:80]}{where}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if test_configs/README.md does not match the measured table",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="replace the generated block in test_configs/README.md in place",
    )
    parser.add_argument(
        "--detail",
        metavar="FIXTURE",
        help="print per-control results for the fixture whose path contains FIXTURE",
    )
    args = parser.parse_args()

    if args.detail:
        return detail(args.detail)

    table = render(*measure_all())

    if not args.check and not args.write:
        print(table)
        return 0

    if not README.exists():
        print(f"{README} does not exist", file=sys.stderr)
        return 1
    current = README.read_text(encoding=FILE_ENCODING)
    match = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), current, re.S)
    if match is None:
        print(
            f"{README.name} has no generated-table markers; run without --check "
            "and paste the output between them.",
            file=sys.stderr,
        )
        return 1

    if args.write:
        if match.group(0) == table:
            print(f"{README.name} table is already up to date.")
            return 0
        # Rewriting only the marked span, never the whole file: everything around
        # the block is hand-written prose that explains the numbers, and a
        # generator that could clobber it would make the explanation the cheapest
        # thing in the file to lose.
        README.write_text(
            current[: match.start()] + table + current[match.end() :],
            encoding=FILE_ENCODING,
        )
        print(f"{README.name} table rewritten; re-read the prose around it.")
        return 0

    if match.group(0).strip() != table.strip():
        print(
            f"{README.name} is stale. Regenerate with:\n"
            "  python scripts/fixture_report.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{README.name} table is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
